spring.application.name=blogApp

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/blogApis
spring.datasource.username=postgres
spring.datasource.password=922792
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging for debugging Hibernate SQL statements and parameters
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Multipart upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

project.image=images/

logging.level.org.springframework.security=DEBUG
